@startuml FfmpegGUI
title "UML Class Diagram"
class FfmpegGui {
    .. Class Variables ..
    _instance: FfmpegGUI
    .. Instance Variables ..
        - _main_layout: QtWidgets.QVBoxLayout
        - _input_label: QtWidgets.QLabel
        - _input_text: QtWidgets.QLineEdit
        - _input_dialog: QtWidgets.QPushButton
        - _input_horizontal: QtWidgets.QHBoxLayout
        - _input_vertical: QtWidgets.QVBoxLayout
        - _output_label: QtWidgets.QLabel
        - _output_text: QtWidgets.QLineEdit
        - _output_extension: QtWidgets.QComboBox
        - _output_horizontal: QtWidgets.QHBoxLayout
        - _output_vertical: QtWidgets.QVBoxLayout
        - _convert_button: QtWidgets.QPushButton
        - _supported_inputs: str
    .. Overloaded Methods ..
        - __init__(): None
    .. Instance Methods ..
        + supported_inputs(): list[str]
        + supported_outputs(): list[str]
    + enable(): None
        + beginconversion(): None
        + promptinputfile(): None
    .. Static Methods ..
        + main(): None
}
@enduml
